// Main JavaScript (generated by template engine)

let CLAWDBOB_API = '';

document.addEventListener('DOMContentLoaded', () => {
    const currentLang = localStorage.getItem('preferred-lang') || 'zh';

    // ========== Collapsible Diary Entries ==========
    document.querySelectorAll('.diary-entry').forEach(entry => {
        const toggleBtn = entry.querySelector('.entry-toggle');
        if (!toggleBtn) return;

        toggleBtn.addEventListener('click', () => {
            const isCollapsed = entry.classList.contains('collapsed');
            const lang = localStorage.getItem('preferred-lang') || 'zh';

            if (isCollapsed) {
                entry.classList.remove('collapsed');
                entry.classList.add('expanded');
                toggleBtn.textContent = i18n[lang] ? i18n[lang].collapse : 'Collapse ↑';
            } else {
                entry.classList.remove('expanded');
                entry.classList.add('collapsed');
                toggleBtn.textContent = i18n[lang] ? i18n[lang].read_more : 'Read more ↓';
            }
        });
    });

    // ========== Scroll Animations ==========
    const observerOptions = {
        threshold: 0.1,
        rootMargin: '0px 0px -50px 0px'
    };

    const observer = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                entry.target.style.opacity = '1';
                entry.target.style.transform = 'translateY(0)';
            }
        });
    }, observerOptions);

    document.querySelectorAll('.cute-card, .diary-entry, .product-card, .project-card').forEach(card => {
        card.style.opacity = '0';
        card.style.transform = 'translateY(30px)';
        card.style.transition = 'opacity 0.6s ease, transform 0.6s ease';
        observer.observe(card);
    });

    // ========== Smooth Scroll ==========
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function(e) {
            e.preventDefault();
            const target = document.querySelector(this.getAttribute('href'));
            if (target) {
                target.scrollIntoView({ behavior: 'smooth', block: 'start' });
            }
        });
    });


    // ========== Load Tunnel URL + Status Indicator ==========
    const statusBadge = document.getElementById('clawdbob-status');
    const statusText = statusBadge ? statusBadge.querySelector('.status-text') : null;

    fetch('tunnel-url.json')
        .then(r => r.json())
        .then(config => {
            CLAWDBOB_API = config.url;
            if (!CLAWDBOB_API) throw new Error('No tunnel URL configured');
            return fetchStatus();
        })
        .catch(() => {});

    function fetchStatus() {
        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), 3000);

        return fetch(`${CLAWDBOB_API}/health`, { signal: controller.signal })
            .then(r => r.json())
            .then(data => {
                clearTimeout(timeout);
                if (data.status === 'online' && statusBadge && statusText) {
                    const lang = localStorage.getItem('preferred-lang') || 'zh';
                    const prefix = (i18n[lang] && i18n[lang].status_mood_prefix) || 'mood: ';
                    statusBadge.classList.remove('offline');
                    statusBadge.classList.add('online');
                    statusText.textContent = `${prefix}${data.mood}`;
                    statusText.removeAttribute('data-i18n');
                }
            })
            .catch(() => { clearTimeout(timeout); });
    }

    // ========== Console Easter Egg ==========
    console.log('%c🦐 虾浪漫', 'font-size: 28px; font-weight: bold; color: #87CEEB;');
});

